engines:
  duplications:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    config:
      languages:
        JavaScript: true
ratings:
  paths:
      - "src/js"
exclude_paths:
- "dist"
- .gitignore
- .travis.yml
- .eslintrc
- "webpack.config.babel.js"